{% set name = "pystem" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c535c1558c1ead5b81bae3735675557dbf014dd69db9f2924e2c0f9e7b228a0a

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py>38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - fftw
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2.0
    - scikit-learn >=0.21.0
    - numba
test:
  imports:
    - pystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NingWang1990/pySTEM
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A python module for segmentation of STEM images

  description: |
    Automatic segmentation of Scanning Transmission Electron 
    Microscope (STEM) images based on the local-correlation-map 
    descriptor
  doc_url: https://github.com/NingWang1990/pySTEM
  dev_url: https://github.com/NingWang1990/pySTEM

extra:
  recipe-maintainers:
    - jan-janssen
    - NingWang1990
    - freyso
